void test_construct_ll_from_array();
void test_add_node();
void test_delete_node();
void test_search_ll();
void test_insert_node_after();
void test_add_node_at_beginning();
void test_delete_node_at_beginning();
void test_search_not_in_ll();
void test_delete_node_at_end();